name: CI Pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install DVC
        run: |
          pip install dvc        

      - name: run pipeline
        env:
          CAPSTONE_TEST: ${{ secrets.CAPSTONE_TEST }}
        run: |
          dvc repro

       

      # - name: ğŸ§ª Run model unit tests
      #   env:
      #     CAPSTONE_TEST: ${{ secrets.CAPSTONE_TEST }}
      #   run: |
      #     python -m unittest tests/test_model.py

      # - name: ğŸ§ª Run Flask app tests
      #   env:
      #     CAPSTONE_TEST: ${{ secrets.CAPSTONE_TEST }}
      #   run: |
      #     python -m unittest tests/test_flask_app.py

      # - name: ğŸ” AWS ECR Login
      #   run: |
      #     aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws configure set region ${{ secrets.AWS_REGION }}
      #     aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      # - name: ğŸ› ï¸ Build Docker image
      #   run: |
      #     docker build -t ${{ secrets.ECR_REPOSITORY }}:latest .

      # - name: ğŸ·ï¸ Tag Docker image
      #   run: |
      #     docker tag ${{ secrets.ECR_REPOSITORY }}:latest \
      #     ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

      # - name: ğŸ” Check Docker Auth
      #   run: docker info

      # - name: ğŸš¢ Push Docker image to ECR
      #   run: |
      #     docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

      # - name: ğŸ“¦ Set Up kubectl
      #   uses: azure/setup-kubectl@v3
      #   with:
      #     version: 'latest'

      # - name: ğŸ”§ Update kubeconfig
      #   run: |
      #     aws eks update-kubeconfig --region us-east-1 --name flask-app-cluster

      # - name: ğŸ” Create Kubernetes Secret
      #   run: |
      #     kubectl create secret generic capstone-secret \
      #       --from-literal=CAPSTONE_TEST=${{ secrets.CAPSTONE_TEST }} --dry-run=client -o yaml | kubectl apply -f -

      # - name: ğŸš€ Deploy to EKS
      #   run: |
      #     kubectl apply -f deployment.yaml
